name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  hygiene:
    name: Hygiene
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: fmt
      run: cargo fmt -- --check
    - name: clippy
      run: cargo clippy --tests

  build:
    name: "Build & Test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - "1.54.0"
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    - name: Test default features
      run: cargo test --verbose
    - name: Test no default features
      run: cargo test --verbose --no-default-features

  doc:
    name: "Doc"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check doc generation
      run: cargo doc --verbose
